output:
  formats:
    - format: line-number
linters:
  enable:
    - goimports
    - gofmt
    - misspell
    - revive
    - loggercheck
linters-settings:
  errcheck:
    # path to a file containing a list of functions to exclude from checking
    # see https://github.com/kisielk/errcheck#excluding-functions for details
    exclude-functions:
      - io/ioutil.WriteFile
      - io/ioutil.ReadFile
      - (github.com/go-kit/log.Logger).Log
      - io.Copy
      - (github.com/opentracing/opentracing-go.Tracer).Inject
  goimports:
    local-prefixes: "github.com/grafana/dskit"
run:
  timeout: 5m
  # List of build tags, all linters use it.
  build-tags:
    - netgo
    - requires_docker
