// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: propagation_tracker.proto

package memberlist

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PropagationTrackerDesc stores beacons for tracking gossip propagation delay
// across the cluster. Beacons are cluster-wide (not per-node) and are keyed
// by a random beacon ID.
type PropagationTrackerDesc struct {
	// Map of beacon_id -> beacon.
	Beacons map[uint64]BeaconDesc `protobuf:"bytes,1,rep,name=beacons,proto3" json:"beacons" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *PropagationTrackerDesc) Reset()      { *m = PropagationTrackerDesc{} }
func (*PropagationTrackerDesc) ProtoMessage() {}
func (*PropagationTrackerDesc) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb1c69f252ca5e51, []int{0}
}
func (m *PropagationTrackerDesc) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PropagationTrackerDesc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PropagationTrackerDesc.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PropagationTrackerDesc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropagationTrackerDesc.Merge(m, src)
}
func (m *PropagationTrackerDesc) XXX_Size() int {
	return m.Size()
}
func (m *PropagationTrackerDesc) XXX_DiscardUnknown() {
	xxx_messageInfo_PropagationTrackerDesc.DiscardUnknown(m)
}

var xxx_messageInfo_PropagationTrackerDesc proto.InternalMessageInfo

func (m *PropagationTrackerDesc) GetBeacons() map[uint64]BeaconDesc {
	if m != nil {
		return m.Beacons
	}
	return nil
}

// Beacon represents a single propagation beacon published to the cluster.
type BeaconDesc struct {
	// Wall-clock timestamp when this beacon was published (milliseconds since epoch).
	PublishedAt int64 `protobuf:"varint,1,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	// Deletion timestamp (milliseconds since epoch). 0 = active, non-zero = beacon deleted at that time (tombstone).
	DeletedAt int64 `protobuf:"varint,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (m *BeaconDesc) Reset()      { *m = BeaconDesc{} }
func (*BeaconDesc) ProtoMessage() {}
func (*BeaconDesc) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb1c69f252ca5e51, []int{1}
}
func (m *BeaconDesc) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BeaconDesc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BeaconDesc.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BeaconDesc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeaconDesc.Merge(m, src)
}
func (m *BeaconDesc) XXX_Size() int {
	return m.Size()
}
func (m *BeaconDesc) XXX_DiscardUnknown() {
	xxx_messageInfo_BeaconDesc.DiscardUnknown(m)
}

var xxx_messageInfo_BeaconDesc proto.InternalMessageInfo

func (m *BeaconDesc) GetPublishedAt() int64 {
	if m != nil {
		return m.PublishedAt
	}
	return 0
}

func (m *BeaconDesc) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*PropagationTrackerDesc)(nil), "memberlist.PropagationTrackerDesc")
	proto.RegisterMapType((map[uint64]BeaconDesc)(nil), "memberlist.PropagationTrackerDesc.BeaconsEntry")
	proto.RegisterType((*BeaconDesc)(nil), "memberlist.BeaconDesc")
}

func init() { proto.RegisterFile("propagation_tracker.proto", fileDescriptor_cb1c69f252ca5e51) }

var fileDescriptor_cb1c69f252ca5e51 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4e, 0x3a, 0x41,
	0x10, 0xc6, 0x77, 0x80, 0xff, 0xdf, 0x38, 0x50, 0x98, 0x2b, 0x08, 0x92, 0x38, 0x22, 0x15, 0x85,
	0x1e, 0x09, 0x5a, 0x18, 0x3b, 0x88, 0xb6, 0x6a, 0x2e, 0xf6, 0xe4, 0xee, 0x58, 0x8f, 0x0b, 0x07,
	0x7b, 0xd9, 0xdb, 0x33, 0xa1, 0xf3, 0x11, 0x7c, 0x0c, 0x5f, 0xc2, 0x9e, 0x92, 0x92, 0xca, 0xc8,
	0xd2, 0x58, 0xf2, 0x08, 0x86, 0x5d, 0x15, 0x0a, 0xbb, 0x99, 0xf9, 0xbe, 0xef, 0xf7, 0x25, 0x83,
	0x87, 0xa9, 0x14, 0xa9, 0x1f, 0xf9, 0x2a, 0x16, 0x93, 0xbe, 0x92, 0x7e, 0x38, 0xe2, 0xd2, 0x4d,
	0xa5, 0x50, 0xc2, 0xc1, 0x31, 0x1f, 0x07, 0x5c, 0x26, 0x71, 0xa6, 0xea, 0x67, 0x51, 0xac, 0x86,
	0x79, 0xe0, 0x86, 0x62, 0xdc, 0x8e, 0x44, 0x24, 0xda, 0xc6, 0x12, 0xe4, 0x8f, 0x66, 0x33, 0x8b,
	0x99, 0x6c, 0xb4, 0xf9, 0x06, 0x58, 0xbd, 0xdf, 0x82, 0x1f, 0x2c, 0xf7, 0x9a, 0x67, 0xa1, 0x73,
	0x87, 0x7b, 0x01, 0xf7, 0x43, 0x31, 0xc9, 0x6a, 0xd0, 0x28, 0xb6, 0xca, 0x9d, 0xb6, 0xbb, 0xed,
	0x71, 0xff, 0x0e, 0xb9, 0x3d, 0x9b, 0xb8, 0x99, 0x28, 0x39, 0xed, 0x95, 0x66, 0xef, 0xc7, 0xcc,
	0xfb, 0xa1, 0xd4, 0x3d, 0xac, 0xec, 0xca, 0xce, 0x01, 0x16, 0x47, 0x7c, 0x5a, 0x83, 0x06, 0xb4,
	0x4a, 0xde, 0x66, 0x74, 0x4e, 0xf1, 0xdf, 0x93, 0x9f, 0xe4, 0xbc, 0x56, 0x68, 0x40, 0xab, 0xdc,
	0xa9, 0xee, 0x16, 0xda, 0xe8, 0xa6, 0xc4, 0xb3, 0xa6, 0xab, 0xc2, 0x25, 0x34, 0x6f, 0x11, 0xb7,
	0x82, 0x73, 0x82, 0x95, 0x34, 0x0f, 0x92, 0x38, 0x1b, 0xf2, 0x41, 0xdf, 0x57, 0x06, 0x5d, 0xf4,
	0xca, 0xbf, 0xb7, 0xae, 0x72, 0x8e, 0x10, 0x07, 0x3c, 0xe1, 0xca, 0x1a, 0x0a, 0xc6, 0xb0, 0xff,
	0x7d, 0xe9, 0xaa, 0xde, 0xc5, 0x7c, 0x49, 0x6c, 0xb1, 0x24, 0xb6, 0x5e, 0x12, 0x3c, 0x6b, 0x82,
	0x57, 0x4d, 0x30, 0xd3, 0x04, 0x73, 0x4d, 0xf0, 0xa1, 0x09, 0x3e, 0x35, 0xb1, 0xb5, 0x26, 0x78,
	0x59, 0x11, 0x9b, 0xaf, 0x88, 0x2d, 0x56, 0xc4, 0x82, 0xff, 0xe6, 0x99, 0xe7, 0x5f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x0e, 0x54, 0xa2, 0x8a, 0xa4, 0x01, 0x00, 0x00,
}

func (this *PropagationTrackerDesc) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PropagationTrackerDesc)
	if !ok {
		that2, ok := that.(PropagationTrackerDesc)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Beacons) != len(that1.Beacons) {
		return false
	}
	for i := range this.Beacons {
		a := this.Beacons[i]
		b := that1.Beacons[i]
		if !(&a).Equal(&b) {
			return false
		}
	}
	return true
}
func (this *BeaconDesc) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*BeaconDesc)
	if !ok {
		that2, ok := that.(BeaconDesc)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.PublishedAt != that1.PublishedAt {
		return false
	}
	if this.DeletedAt != that1.DeletedAt {
		return false
	}
	return true
}
func (this *PropagationTrackerDesc) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&memberlist.PropagationTrackerDesc{")
	keysForBeacons := make([]uint64, 0, len(this.Beacons))
	for k, _ := range this.Beacons {
		keysForBeacons = append(keysForBeacons, k)
	}
	github_com_gogo_protobuf_sortkeys.Uint64s(keysForBeacons)
	mapStringForBeacons := "map[uint64]BeaconDesc{"
	for _, k := range keysForBeacons {
		mapStringForBeacons += fmt.Sprintf("%#v: %#v,", k, this.Beacons[k])
	}
	mapStringForBeacons += "}"
	if this.Beacons != nil {
		s = append(s, "Beacons: "+mapStringForBeacons+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *BeaconDesc) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&memberlist.BeaconDesc{")
	s = append(s, "PublishedAt: "+fmt.Sprintf("%#v", this.PublishedAt)+",\n")
	s = append(s, "DeletedAt: "+fmt.Sprintf("%#v", this.DeletedAt)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringPropagationTracker(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *PropagationTrackerDesc) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PropagationTrackerDesc) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PropagationTrackerDesc) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Beacons) > 0 {
		for k := range m.Beacons {
			v := m.Beacons[k]
			baseI := i
			{
				size, err := (&v).MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPropagationTracker(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
			i = encodeVarintPropagationTracker(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintPropagationTracker(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *BeaconDesc) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BeaconDesc) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BeaconDesc) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DeletedAt != 0 {
		i = encodeVarintPropagationTracker(dAtA, i, uint64(m.DeletedAt))
		i--
		dAtA[i] = 0x10
	}
	if m.PublishedAt != 0 {
		i = encodeVarintPropagationTracker(dAtA, i, uint64(m.PublishedAt))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintPropagationTracker(dAtA []byte, offset int, v uint64) int {
	offset -= sovPropagationTracker(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PropagationTrackerDesc) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Beacons) > 0 {
		for k, v := range m.Beacons {
			_ = k
			_ = v
			l = v.Size()
			mapEntrySize := 1 + sovPropagationTracker(uint64(k)) + 1 + l + sovPropagationTracker(uint64(l))
			n += mapEntrySize + 1 + sovPropagationTracker(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *BeaconDesc) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PublishedAt != 0 {
		n += 1 + sovPropagationTracker(uint64(m.PublishedAt))
	}
	if m.DeletedAt != 0 {
		n += 1 + sovPropagationTracker(uint64(m.DeletedAt))
	}
	return n
}

func sovPropagationTracker(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPropagationTracker(x uint64) (n int) {
	return sovPropagationTracker(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *PropagationTrackerDesc) String() string {
	if this == nil {
		return "nil"
	}
	keysForBeacons := make([]uint64, 0, len(this.Beacons))
	for k, _ := range this.Beacons {
		keysForBeacons = append(keysForBeacons, k)
	}
	github_com_gogo_protobuf_sortkeys.Uint64s(keysForBeacons)
	mapStringForBeacons := "map[uint64]BeaconDesc{"
	for _, k := range keysForBeacons {
		mapStringForBeacons += fmt.Sprintf("%v: %v,", k, this.Beacons[k])
	}
	mapStringForBeacons += "}"
	s := strings.Join([]string{`&PropagationTrackerDesc{`,
		`Beacons:` + mapStringForBeacons + `,`,
		`}`,
	}, "")
	return s
}
func (this *BeaconDesc) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&BeaconDesc{`,
		`PublishedAt:` + fmt.Sprintf("%v", this.PublishedAt) + `,`,
		`DeletedAt:` + fmt.Sprintf("%v", this.DeletedAt) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringPropagationTracker(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *PropagationTrackerDesc) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPropagationTracker
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PropagationTrackerDesc: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PropagationTrackerDesc: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Beacons", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPropagationTracker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPropagationTracker
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPropagationTracker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Beacons == nil {
				m.Beacons = make(map[uint64]BeaconDesc)
			}
			var mapkey uint64
			mapvalue := &BeaconDesc{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPropagationTracker
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowPropagationTracker
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowPropagationTracker
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthPropagationTracker
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthPropagationTracker
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &BeaconDesc{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipPropagationTracker(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthPropagationTracker
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Beacons[mapkey] = *mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPropagationTracker(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPropagationTracker
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPropagationTracker
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BeaconDesc) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPropagationTracker
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BeaconDesc: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BeaconDesc: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublishedAt", wireType)
			}
			m.PublishedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPropagationTracker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PublishedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeletedAt", wireType)
			}
			m.DeletedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPropagationTracker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeletedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPropagationTracker(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPropagationTracker
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPropagationTracker
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPropagationTracker(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPropagationTracker
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPropagationTracker
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPropagationTracker
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPropagationTracker
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthPropagationTracker
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowPropagationTracker
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipPropagationTracker(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthPropagationTracker
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthPropagationTracker = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPropagationTracker   = fmt.Errorf("proto: integer overflow")
)
