---
{
   "kind": "pipeline",
   "name": "validate-pr",
   "steps": [
      {
         "commands": [
            "make mod-check"
         ],
         "image": "golang:1.18.4",
         "name": "make-mod-check"
      },
      {
         "commands": [
            "make lint"
         ],
         "depends_on": [
            "make-mod-check"
         ],
         "image": "golang:1.18.4",
         "name": "make-lint"
      },
      {
         "commands": [
            "make test"
         ],
         "depends_on": [
            "make-lint"
         ],
         "image": "golang:1.18.4",
         "name": "make-test (go 1.18.4)"
      },
      {
         "commands": [
            "make test"
         ],
         "depends_on": [
            "make-lint"
         ],
         "image": "golang:1.19.3",
         "name": "make-test (go 1.19.3)"
      },
      {
         "commands": [
            "make test"
         ],
         "depends_on": [
            "make-lint"
         ],
         "image": "golang:1.20.4",
         "name": "make-test (go 1.20.4)"
      },
      {
         "commands": [
            "apt-get update && apt-get -y install unzip",
            "go mod vendor",
            "make check-protos"
         ],
         "depends_on": [
            "make-mod-check"
         ],
         "image": "golang:1.18.4",
         "name": "make-check-protos"
      }
   ]
}
---
kind: signature
hmac: 8d1c99ea3689b8cbf6aea9396160f1db269c4d0e9609924b97a674c585178a0b

...
