---
{
   "kind": "pipeline",
   "name": "validate-pr",
   "steps": [
      {
         "commands": [
            "make mod-check"
         ],
         "image": "golang:1.21.0",
         "name": "make-mod-check"
      },
      {
         "commands": [
            "make lint"
         ],
         "depends_on": [
            "make-mod-check"
         ],
         "image": "golang:1.21.0",
         "name": "make-lint"
      },
      {
         "commands": [
            "make test"
         ],
         "depends_on": [
            "make-lint"
         ],
         "image": "golang:1.19.3",
         "name": "make-test (go 1.19.3)"
      },
      {
         "commands": [
            "make test"
         ],
         "depends_on": [
            "make-lint"
         ],
         "image": "golang:1.20.4",
         "name": "make-test (go 1.20.4)"
      },
      {
         "commands": [
            "make test"
         ],
         "depends_on": [
            "make-lint"
         ],
         "image": "golang:1.21.0",
         "name": "make-test (go 1.21.0)"
      },
      {
         "commands": [
            "apt-get update && apt-get -y install unzip",
            "go mod vendor",
            "make check-protos"
         ],
         "depends_on": [
            "make-mod-check"
         ],
         "image": "golang:1.21.0",
         "name": "make-check-protos"
      }
   ]
}
---
kind: signature
hmac: cc85df30ab5ea7fb028057d36dec2fb6676df9343afbac6bdc9ea99b2c913b74

...
