---
{
   "kind": "pipeline",
   "name": "validate-pr",
   "steps": [
      {
         "commands": [
            "make mod-check"
         ],
         "image": "golang:1.20.4",
         "name": "make-mod-check"
      },
      {
         "commands": [
            "make lint"
         ],
         "depends_on": [
            "make-mod-check"
         ],
         "image": "golang:1.20.4",
         "name": "make-lint"
      },
      {
         "commands": [
            "make test"
         ],
         "depends_on": [
            "make-lint"
         ],
         "image": "golang:1.19.3",
         "name": "make-test (go 1.19.3)"
      },
      {
         "commands": [
            "make test"
         ],
         "depends_on": [
            "make-lint"
         ],
         "image": "golang:1.20.4",
         "name": "make-test (go 1.20.4)"
      },
      {
         "commands": [
            "apt-get update && apt-get -y install unzip",
            "go mod vendor",
            "make check-protos"
         ],
         "depends_on": [
            "make-mod-check"
         ],
         "image": "golang:1.20.4",
         "name": "make-check-protos"
      }
   ]
}
---
kind: signature
hmac: ee344abb0ee88da8a963ac73a95cbdb417f8612b23e6d329cb5ab55da16a6a46

...
