---
{
   "kind": "pipeline",
   "name": "validate-pr",
   "steps": [
      {
         "commands": [
            "make mod-check"
         ],
         "image": "golang:1.17.6",
         "name": "make-mod-check"
      },
      {
         "commands": [
            "make lint"
         ],
         "image": "golang:1.17.6",
         "name": "make-lint"
      },
      {
         "commands": [
            "make test"
         ],
         "image": "golang:1.17.6",
         "name": "make-test"
      },
      {
         "commands": [
            "apt-get update && apt-get -y install unzip",
            "go mod vendor",
            "make check-protos"
         ],
         "image": "golang:1.17.6",
         "name": "make-check-protos"
      }
   ]
}
---
kind: signature
hmac: ece0e7c96218aed975b8e9fa0399bee2a8b0d72bbe3ce0830d39fdc84d238b7a

...
