---
{
   "kind": "pipeline",
   "name": "validate-pr",
   "steps": [
      {
         "commands": [
            "make mod-check"
         ],
         "image": "golang:1.18.4",
         "name": "make-mod-check"
      },
      {
         "commands": [
            "make lint"
         ],
         "image": "golang:1.18.4",
         "name": "make-lint"
      },
      {
         "commands": [
            "make test"
         ],
         "image": "golang:1.18.4",
         "name": "make-test (go 1.18.4)"
      },
      {
         "commands": [
            "make test"
         ],
         "image": "golang:1.19.3",
         "name": "make-test (go 1.19.3)"
      },
      {
         "commands": [
            "apt-get update && apt-get -y install unzip",
            "go mod vendor",
            "make check-protos"
         ],
         "image": "golang:1.18.4",
         "name": "make-check-protos"
      }
   ]
}
---
kind: signature
hmac: b9e3e4dbdfad99c1969c6617ed95fe1f32e2a111c7b51690311bd4bb17a18397

...
