---
{
   "kind": "pipeline",
   "name": "validate-pr",
   "steps": [
      {
         "commands": [
            "make mod-check"
         ],
         "image": "golang:1.22.5",
         "name": "make-mod-check"
      },
      {
         "commands": [
            "make lint"
         ],
         "depends_on": [
            "make-mod-check"
         ],
         "image": "golang:1.22.5",
         "name": "make-lint"
      },
      {
         "commands": [
            "make test"
         ],
         "depends_on": [
            "make-lint"
         ],
         "image": "golang:1.21.12",
         "name": "make-test (go 1.21.12)"
      },
      {
         "commands": [
            "make test"
         ],
         "depends_on": [
            "make-lint"
         ],
         "image": "golang:1.22.5",
         "name": "make-test (go 1.22.5)"
      },
      {
         "commands": [
            "make test-benchmarks"
         ],
         "depends_on": [
            "make-lint"
         ],
         "image": "golang:1.22.5",
         "name": "make-test-benchmarks (go 1.22.5)"
      },
      {
         "commands": [
            "apt-get update && apt-get -y install unzip",
            "go mod vendor",
            "make check-protos"
         ],
         "depends_on": [
            "make-mod-check"
         ],
         "image": "golang:1.22.5",
         "name": "make-check-protos"
      }
   ]
}
---
kind: signature
hmac: 4a0bc0860a88f942fc51521193425e8e3c09b4a6731d7b7458212919ce87a12c

...
